v
. There are no for-real comments in KitKat -- mostly because I'm lazy, but not
. entirely because of that. I realized that we don't need to have a comment
. structure in the language because comments are just text in a program which
. isn't executed. Well, to do that in KitKat you just need to steer the program
. around your comment text. Like this. This is one big piece of text which is
. never executed, i.e. a comment.
.
>Look at the source!
